# Generated by Django 2.1.7 on 2019-06-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requiredpeople',
            name='leading',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='leading', to='maket.Collect'),
            preserve_default=False,
        ),
    ]
